version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11   # CircleCI’s official Python 3.11 image
    steps:
      - checkout                  # Pulls down your repo into the build
      - run:
          name: Install dependencies
          command: pip install requests
      - run:
          name: Run unit tests
          command: python -m unittest discover -s . -p "test_*.py" -v

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
